/-
Copyright (c) 2026 Benedikt Fauseweh. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Benedikt Fauseweh
-/
module

public import Physlib.QuantumMechanics.FiniteTarget.Basic
/-!

# The Lieb–Robinson bound

## i. Overview

The Lieb–Robinson bound establishes a finite group velocity for the propagation of
information in a quantum spin system with short-range interactions on a lattice. The
seminal result is

* E. H. Lieb and D. W. Robinson, *The Finite Group Velocity of Quantum Spin Systems*,
  Commun. Math. Phys. **28**, 251–257 (1972).

In this module we set up the basic definitions required to *state* the bound on a
finite lattice with finite-range interactions, the scenario of the 1972 paper.

The lattice is a finite type `V` equipped with a pseudo-metric. At every site we
place a copy of an `N`-dimensional complex Hilbert space; the total Hilbert space
is realised as `EuclideanSpace ℂ (V → Fin N)`, i.e. the L²-space on the set of
configurations `V → Fin N`. The observable algebra is the algebra of continuous
linear endomorphisms of this Hilbert space. An interaction `Φ` assigns to every
finite subset `X ⊆ V` a self-adjoint operator supported on `X`, with a uniform
bound `range : ℝ` on the diameter of subsets that carry non-trivial interactions.
The Hamiltonian is the sum `∑_X Φ(X)`; the dynamics is the unitary group
generated by it, defined via `QuantumMechanics.FiniteTarget.timeEvolution`.

The Lieb–Robinson theorem is stated at the end of the file as a `sorry`-ed
existence statement; its proof is not addressed here.

## ii. Key results

- `TotalHilbertSpace` : the many-body Hilbert space `EuclideanSpace ℂ (V → Fin N)`.
- `Operator` : the algebra of observables `TotalHilbertSpace →L[ℂ] TotalHilbertSpace`.
- `IsSupportedOn` : the predicate that an operator is supported on a subset of sites.
- `LocalObservable` : a bundled operator supported on a given subset.
- `Interaction` : a finite-range interaction `Φ` with self-adjoint local terms.
- `Interaction.hamiltonian` : the Hamiltonian `H = ∑_X Φ(X)`.
- `Interaction.heisenberg` : the Heisenberg-evolved observable `τ_t(A) = e^{itH} A e^{-itH}`.
- `liebRobinsonBound` : the statement of the Lieb–Robinson bound (proof deferred).

## iii. Table of contents

- A. The lattice and per-site setup
- B. The total Hilbert space
  - B.1. Definition
  - B.2. Instances and dimension
  - B.3. Configuration basis
- C. Operators and commutator
  - C.1. The operator type
  - C.2. The commutator
- D. Support of an operator
  - D.1. Definition of `IsSupportedOn`
  - D.2. Bundled local observable
- E. Interactions
- F. The Hamiltonian
- G. Time evolution via `FiniteTarget`
- H. Statement of the Lieb–Robinson bound

## iv. References

- E. H. Lieb and D. W. Robinson, *The Finite Group Velocity of Quantum Spin Systems*,
  Commun. Math. Phys. **28**, 251–257 (1972).
- B. Nachtergaele, Y. Ogata, and R. Sims, *Propagation of Correlations in Quantum
  Lattice Systems*, J. Stat. Phys. **124**, 1–13 (2006).

-/

@[expose] public section

namespace CondensedMatter

namespace LiebRobinson

open scoped InnerProductSpace

/-!

## A. The lattice and per-site setup

The lattice is an arbitrary finite type `V` with a pseudo-metric, and the
single-site Hilbert space has uniform dimension `N`.

-/

/-!

## B. The total Hilbert space

### B.1. Definition

-/

/-- The many-body Hilbert space of a quantum spin system on the lattice `V` with
`N`-dimensional single-site Hilbert spaces, realised as the `L²`-space on the set
of configurations `V → Fin N`. -/
abbrev TotalHilbertSpace (V : Type*) (N : ℕ) :=
  EuclideanSpace ℂ (V → Fin N)

/-!

### B.2. Instances and dimension

All the structural instances we need on `TotalHilbertSpace` are inherited from
`EuclideanSpace`.

-/

section Instances

variable (V : Type*) [Fintype V] [DecidableEq V] (N : ℕ)

noncomputable instance : NormedAddCommGroup (TotalHilbertSpace V N) :=
  inferInstanceAs (NormedAddCommGroup (EuclideanSpace ℂ (V → Fin N)))

noncomputable instance : InnerProductSpace ℂ (TotalHilbertSpace V N) :=
  inferInstanceAs (InnerProductSpace ℂ (EuclideanSpace ℂ (V → Fin N)))

instance : CompleteSpace (TotalHilbertSpace V N) :=
  inferInstanceAs (CompleteSpace (EuclideanSpace ℂ (V → Fin N)))

instance : FiniteDimensional ℂ (TotalHilbertSpace V N) :=
  inferInstanceAs (FiniteDimensional ℂ (EuclideanSpace ℂ (V → Fin N)))

/-- The dimension of `TotalHilbertSpace V N` is `N ^ |V|`. -/
lemma finrank_totalHilbertSpace :
    Module.finrank ℂ (TotalHilbertSpace V N) = N ^ Fintype.card V := by
  simp [TotalHilbertSpace, finrank_euclideanSpace]

end Instances

/-!

### B.3. Configuration basis

The standard orthonormal basis of `TotalHilbertSpace V N` is indexed by
configurations `s : V → Fin N`.

-/

/-- The configuration ket `|s⟩` for `s : V → Fin N`, defined as the standard basis
vector of `EuclideanSpace ℂ (V → Fin N)` at index `s`. -/
noncomputable def configState {V : Type*} [Fintype V] [DecidableEq V] {N : ℕ}
    (s : V → Fin N) : TotalHilbertSpace V N :=
  EuclideanSpace.basisFun (V → Fin N) ℂ s

/-!

## C. Operators and commutator

### C.1. The operator type

-/

/-- The algebra of observables on the lattice: continuous linear endomorphisms of
the total Hilbert space. Since `TotalHilbertSpace V N` is finite-dimensional this
is the same as the algebra of arbitrary linear endomorphisms, but the bundled
continuous form matches `Physlib.QuantumMechanics.FiniteTarget`. -/
abbrev Operator (V : Type*) [Fintype V] [DecidableEq V] (N : ℕ) :=
  TotalHilbertSpace V N →L[ℂ] TotalHilbertSpace V N

/-!

### C.2. The commutator

The Lie bracket `⁅A, B⁆ = A * B - B * A` from Mathlib is used throughout; no
custom definition is introduced.

-/

/-!

## D. Support of an operator

### D.1. Definition of `IsSupportedOn`

An operator is *supported on* a subset `X ⊆ V` when it can act non-trivially
only via the components of its input that lie in `X`. We encode this via matrix
elements: if two configurations `s` and `t` already disagree somewhere on the
complement `Xᶜ`, the operator cannot produce a transition between them.

This is one of several equivalent characterisations (the others being via the
commutant of the algebra on `Xᶜ`, or a partial-trace factorisation). The
configuration-element form chosen here has the advantage of being completely
elementary.

-/

/-- An operator `A : Operator V N` is *supported on* the finite subset `X ⊆ V`
when its matrix elements between configurations that disagree somewhere outside
`X` vanish. -/
def IsSupportedOn {V : Type*} [Fintype V] [DecidableEq V] {N : ℕ}
    (X : Finset V) (A : Operator V N) : Prop :=
  ∀ s t : V → Fin N,
    (∃ x : V, x ∉ X ∧ s x ≠ t x) → ⟪configState s, A (configState t)⟫_ℂ = 0

/-!

### D.2. Bundled local observable

-/

/-- A *local observable* supported on a finite subset `X ⊆ V` of lattice sites,
bundled with the support property. -/
structure LocalObservable (V : Type*) [Fintype V] [DecidableEq V] (N : ℕ)
    (X : Finset V) where
  /-- The underlying operator. -/
  op : Operator V N
  /-- The operator is supported on `X`. -/
  isSupported : IsSupportedOn X op

/-!

## E. Interactions

A finite-range interaction is a self-adjoint operator-valued function on the
finite subsets of `V`, vanishing on subsets of diameter larger than a fixed
range.

-/

/-- A finite-range interaction on the lattice `V` with single-site dimension `N`.

`Φ X` is the local interaction term carried by the finite subset `X ⊆ V`. It is
required to be self-adjoint and supported on `X`, and to vanish whenever the
diameter of `X` exceeds the fixed `range`. -/
structure Interaction (V : Type*) [Fintype V] [DecidableEq V] [PseudoMetricSpace V]
    (N : ℕ) where
  /-- The map assigning a local operator to each finite subset of `V`. -/
  Φ : Finset V → Operator V N
  /-- A uniform upper bound on the diameter of subsets carrying a non-zero
  interaction term. -/
  range : ℝ
  /-- The range is non-negative. -/
  range_nonneg : 0 ≤ range
  /-- Each term `Φ X` is supported on `X`. -/
  Φ_supported : ∀ X, IsSupportedOn X (Φ X)
  /-- Each term `Φ X` is self-adjoint. -/
  Φ_selfAdjoint : ∀ X, IsSelfAdjoint (Φ X)
  /-- Subsets with diameter exceeding `range` carry no interaction. -/
  range_bounded : ∀ X : Finset V, range < Metric.diam (X : Set V) → Φ X = 0

namespace Interaction

variable {V : Type*} [Fintype V] [DecidableEq V] [PseudoMetricSpace V] {N : ℕ}

/-!

## F. The Hamiltonian

-/

/-- The Hamiltonian of the interaction, `H = ∑_{X ⊆ V} Φ(X)`. -/
noncomputable def hamiltonian (Φ : Interaction V N) : Operator V N :=
  ∑ X ∈ (Finset.univ : Finset V).powerset, Φ.Φ X

/-- The Hamiltonian of a finite-range interaction is self-adjoint. -/
lemma hamiltonian_isSelfAdjoint (Φ : Interaction V N) :
    IsSelfAdjoint Φ.hamiltonian :=
  isSelfAdjoint_sum (R := Operator V N) _ (fun X _ => Φ.Φ_selfAdjoint X)

/-!

## G. Time evolution via `FiniteTarget`

We package an interaction as a `QuantumMechanics.FiniteTarget` and reuse the
exponential-based time-evolution definition from there.

-/

/-- Package the interaction as a finite-target quantum system, so that we can
reuse the time-evolution machinery of `Physlib.QuantumMechanics.FiniteTarget`. -/
noncomputable def toFiniteTarget (Φ : Interaction V N) :
    QuantumMechanics.FiniteTarget (TotalHilbertSpace V N) (N ^ Fintype.card V) where
  hdim := finrank_totalHilbertSpace V N
  Ham := Φ.hamiltonian
  Ham_selfAdjoint := Φ.hamiltonian_isSelfAdjoint

/-- The unitary time-evolution operator `e^{-i t H / ℏ}` for the interaction `Φ`.
Inherited from `QuantumMechanics.FiniteTarget.timeEvolution`. -/
noncomputable def evolutionUnitary (Φ : Interaction V N) (t : ℝ) : Operator V N :=
  Φ.toFiniteTarget.timeEvolution t

/-- The Heisenberg-evolved observable `τ_t(A) = e^{itH/ℏ} A e^{-itH/ℏ}`. -/
noncomputable def heisenberg (Φ : Interaction V N) (t : ℝ) (A : Operator V N) :
    Operator V N :=
  Φ.evolutionUnitary (-t) * A * Φ.evolutionUnitary t

end Interaction

/-!

## H. Statement of the Lieb–Robinson bound

For every finite-range interaction `Φ` there exist a finite group velocity
`vΦ ≥ 0` and a strictly positive decay rate `μ(v)` on `(vΦ, ∞)` such that, for
all local observables `A` and `B` supported on disjoint subsets, the commutator
`⁅τ_t(A), B⁆` decays exponentially in `d(X, Y) - v |t|` whenever the latter is
positive.

The separation between two subsets is expressed pointwise: we require
`v |t| < dist x y` for every `x ∈ X` and `y ∈ Y`.

The proof is not addressed in this file.

-/

/-- **Lieb–Robinson bound** (existence form).

For every finite-range interaction `Φ` on a finite lattice with a pseudo-metric
there exists a finite group velocity `vΦ ≥ 0` and a strictly positive decay
function `μ` on `(vΦ, ∞)` such that, for all local observables
`A : LocalObservable V N X` and `B : LocalObservable V N Y`, all times `t`, and
all `v > vΦ`, whenever every pair `(x, y) ∈ X × Y` satisfies `v |t| < dist x y`,

    ‖⁅τ_t(A), B⁆‖ ≤ 2 ‖A‖ ‖B‖ · |X| · |Y| ·
                      exp(-(μ v) · (dist x y - v |t|))   for all (x, y).

The proof is the subject of a forthcoming contribution. -/
theorem liebRobinsonBound {V : Type*} [Fintype V] [DecidableEq V] [PseudoMetricSpace V]
    {N : ℕ} (Φ : Interaction V N) :
    ∃ vΦ : ℝ, 0 ≤ vΦ ∧ ∃ μ : ℝ → ℝ,
      (∀ v, vΦ < v → 0 < μ v) ∧
      ∀ {X Y : Finset V} (A : LocalObservable V N X) (B : LocalObservable V N Y)
        (t : ℝ) (v : ℝ),
        vΦ < v → (∀ x ∈ X, ∀ y ∈ Y, v * |t| < dist x y) →
        ∀ x ∈ X, ∀ y ∈ Y,
          ‖⁅Φ.heisenberg t A.op, B.op⁆‖ ≤
            2 * ‖A.op‖ * ‖B.op‖ * (X.card : ℝ) * (Y.card : ℝ) *
              Real.exp (- μ v * (dist x y - v * |t|)) := by
  sorry

end LiebRobinson

end CondensedMatter
